{{- if or (and .Values.mcp.authToken (not .Values.mcp.existingAuthSecret)) (and .Values.n8n.enabled .Values.n8n.apiKey (not .Values.n8n.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n-mcp-server.fullname" . }}-credentials
  labels:
    {{- include "n8n-mcp-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.mcp.authToken (not .Values.mcp.existingAuthSecret) }}
  # MCP Auth Token for HTTP mode
  MCP_AUTH_TOKEN: {{ .Values.mcp.authToken | b64enc | quote }}
  {{- end }}

  {{- if and .Values.n8n.enabled .Values.n8n.apiKey (not .Values.n8n.existingSecret) }}
  # n8n API Key
  N8N_API_KEY: {{ .Values.n8n.apiKey | b64enc | quote }}
  {{- end }}
{{- end }}
